name: 1. Manual Patch
permissions: write-all
env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  org_input: ${{ inputs.org }}
  org_event_input: ${{ github.event.inputs.org }}
on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Which "Revanced" do you want to patch?'
        required: true
        default: 'Revanced'
        type: choice
        options:
          - 'Revanced'
          - 'Revanced Extended Arsclib'
          - 'Twitter Piko Stable'
          - 'Revanced Experiments'
          - 'BiliRoamingM'
          - 'Scrazzz Patches'
          - 'Dropped Patches'
          - 'Instafel'
  workflow_call:
    inputs:
      org:
        required: true
        type: string
jobs:
  patch_rv:
    name: Patch Revanced Stable
    if: ${{ github.event.inputs.org == 'Revanced' || inputs.org == 'Revanced' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        run: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rv
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rv
        if: steps.check-gh-rv.outputs.internet_error == '0'
        run: bash src/build/Revanced.sh ${{ matrix.run }}
      - name: Releasing APK files
        id: release-rv
        if: steps.check-gh-rv.outputs.internet_error == '0'
        uses: ./.github/actions/release

  patch_rve_arsclib:
    name: Patch Revanced Extended Arsclib
    if: ${{ github.event.inputs.org == 'Revanced Extended Arsclib' || inputs.org == 'Revanced Extended Arsclib' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rve-arsclib
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve-arsclib
        if: steps.check-gh-rve-arsclib.outputs.internet_error == '0'
        run: bash src/build/Revanced-Extended-Arsclib.sh
      - name: Releasing APK files
        id: release-rve-arsclib
        if: steps.check-gh-rve-arsclib.outputs.internet_error == '0'
        uses: ./.github/actions/release

  patch_twitter_piko_stable:
    name: Patch Twitter Piko Stable
    if: ${{ github.event.inputs.org == 'Twitter Piko Stable' || inputs.org == 'Twitter Piko Stable' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-piko-stable
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-piko-stable
        if: steps.check-gh-piko-stable.outputs.internet_error == '0'
        run: bash src/build/Piko.sh
      - name: Releasing APK files
        id: release-piko-stable
        if: steps.check-gh-piko-stable.outputs.internet_error == '0'
        uses: ./.github/actions/release

  patch_rv_experiments:
    name: Patch Revanced Experiments
    if: ${{ github.event.inputs.org == 'Revanced Experiments' || inputs.org == 'Revanced Experiments' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-rv-experiments
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rv-experiments
        if: steps.check-gh-rv-experiments.outputs.internet_error == '0'
        run: bash src/build/Revanced-Experiment.sh
      - name: Releasing APK files
        id: release-rv-experiments
        if: steps.check-gh-rv-experiments.outputs.internet_error == '0'
        uses: ./.github/actions/release

  patch_BiliRoamingM:
    name: Patch BiliRoamingM
    if: ${{ github.event.inputs.org == 'BiliRoamingM' || inputs.org == 'BiliRoamingM' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-BiliRoamingM
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-BiliRoamingM
        if: steps.check-gh-BiliRoamingM.outputs.internet_error == '0'
        run: bash src/build/BiliRoamingM.sh
      - name: Releasing APK files
        id: release-BiliRoamingM
        if: steps.check-gh-BiliRoamingM.outputs.internet_error == '0'
        uses: ./.github/actions/release

  patch_scrazzz_Patches:
    name: Scrazzz Patches Revanced
    if: ${{ github.event.inputs.org == 'Scrazzz Patches' || inputs.org == 'Scrazzz Patches' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-scrazzz-patches
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-scrazzz-patches
        if: steps.check-gh-scrazzz-patches.outputs.internet_error == '0'
        run: bash src/build/scrazzz-revanced.sh
      - name: Releasing APK files
        id: release-scrazzz-patches
        if: steps.check-gh-scrazzz-patches.outputs.internet_error == '0'
        uses: ./.github/actions/release

  patch_Dropped_Patches:
    name: Dropped Patches Revanced
    if: ${{ github.event.inputs.org == 'Dropped Patches' || inputs.org == 'Dropped Patches' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-Dropped-Patches
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-Dropped-Patches
        if: steps.check-gh-Dropped-Patches.outputs.internet_error == '0'
        run: bash src/build/Dropped-Patches-Revanced.sh
      - name: Releasing APK files
        id: release-Dropped-Patches
        if: steps.check-gh-Dropped-Patches.outputs.internet_error == '0'
        uses: ./.github/actions/release

  patch_Instafel:
    name: Patch Instafel
    if: ${{ github.event.inputs.org == 'Instafel' || inputs.org == 'Instafel' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-Instafel
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-Instafel
        if: steps.check-gh-Instafel.outputs.internet_error == '0'
        run: bash src/build/Instafel.sh
      - name: Releasing APK files
        id: release-Instafel
        if: steps.check-gh-Instafel.outputs.internet_error == '0'
        uses: ./.github/actions/release
